### ISSUE TITLE
Change .desktop file

### ISSUE THREAD

**Issue by Gavcheg** [sde-gui/spicview#4]
I think is better to left only one category in spicview.desktop file. "Graphics" enought.
Also many icon set's know nothing about spicview, so default icon not match system theme. I change Icon=spicview to Icon=gpicview and now all fine. But need better fix, i think.

**Comment by geekless** [comment]
The Categories field is filled according to https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html

The application icon is, obviously, related to the application, not to a thrid-party icon set.
It makes no sence if we use gpicview as an icon name for spicview. What if gpicview is not installed? What if no icon set containing that icon is installed?

According to https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html, the default application icons is located at $(datadir)/icons/hicolor/\*/apps. An icon set can override them by placing stuff in $(datadir)/icons/icon-set-name/\*/apps. If your icon set contains no spicview icon, you can symlink $(datadir)/icons/icon-set-name/48x48/apps/spicview.png to any icon you prefer. Or you can edit the desktop file, of course. But this is not something that should be done in the application's distribution files.
